- name: quicktok
  gather_facts: false
  hosts: [all]
  become: yes

  tasks:

    - name: Create quicktok
      docker_container:
        name: quicktok
        image: lopnesh/quicktok
        pull: true
        state: started
        ports:
          - "0.0.0.0:3000:3000/tcp"